# GitHub CI build pipeline
name: Awesome JSON CI build for NG RN SDK

on:
    push:
        branches:
            - 'release/rtc-ng/4.0.0-framework'
    pull_request:
        branches:
            - 'release/rtc-ng/4.0.0-framework'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  cd xml2json
                  python -m pip install --upgrade pip
                  if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Run json creation
              run: |
                  cd xml2json
                  echo "Running for RN NG"
                  python xml2json.py --working_dir ../dita/RTC-NG --platform_tag rn --json_file rn_cn_ng.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path rn-ng
            - name: Run json creation
              if: always()
              run: |
                  cd xml2json
                  echo "Running for RN NG"
                  python xml2json.py --working_dir ../en-US/dita/RTC-NG --platform_tag rn --json_file rn_en_ng.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path rn-ng
            - name: Upload RN NG JSON to release
              if: always()
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/rn_cn_ng.json
                  asset_name: rn_ng_json_template_cn.json
                  tag: main
                  overwrite: true
                  body: "Template file for automatic comment population."
            - name: Upload RN NG JSON to release
              if: always()
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/rn_en_ng.json
                  asset_name: rn_ng_json_template_en.json
                  tag: main
                  overwrite: true
                  body: "Template file for automatic comment population."
