# This workflow will use OxygenScript to build features.

name: Awesome OxygenScript for DITA doc building (FC)

on:
  #push:
    # branches: [ master, 'release/**' ]
    # branches: [ master ]

  pull_request:
    # branches: [ 'release/rtc/3.6.2-all' ]
    branches: [ 'release/flexible-classroom/2.7.0' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: montudor/action-zip@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.332+9'
        distribution: 'temurin'
    - name: DITA doc building
      run: |
          cd scripts/oxygen/scripts
          
          echo "Start building documentation for FC EN Android"
          echo "-----------------------------------------------------------------------------------------------"
          echo "-----------------------------------------------------------------------------------------------"
          ./transform.sh -i ../../../en-US/dita/flexible-classroom/edu-context/Edu_Context_API_Android.ditamap -sn "DITA Map HTML5 - Flexible-EN-Android" -s ../../../.github/workflows/fcr-en-transformation.scenarios -v
          
          echo "Start building documentation for FC CN Android"
          echo "-----------------------------------------------------------------------------------------------"
          echo "-----------------------------------------------------------------------------------------------"
          ./transform.sh -i ../../../dita/flexible-classroom/edu-context/Edu_Context_API_Android.ditamap -sn "DITA Map HTML5 - Flexible-CN-Android" -s ../../../.github/workflows/fcr-cn-transformation.scenarios -v
          
          echo "Start building documentation for FC EN iOS"
          echo "-----------------------------------------------------------------------------------------------"
          echo "-----------------------------------------------------------------------------------------------"
          ./transform.sh -i ../../../en-US/dita/flexible-classroom/edu-context/Edu_Context_API_iOS.ditamap -sn "DITA Map HTML5 - Flexible-EN-iOS" -s ../../../.github/workflows/fcr-en-transformation.scenarios -v
          
          echo "Start building documentation for FC CN iOS"
          echo "-----------------------------------------------------------------------------------------------"
          echo "-----------------------------------------------------------------------------------------------"
          ./transform.sh -i ../../../dita/flexible-classroom/edu-context/Edu_Context_API_iOS.ditamap -sn "DITA Map HTML5 - Flexible-CN-iOS" -s ../../../.github/workflows/fcr-cn-transformation.scenarios -v
          

    - name: zip files
      run: |
          cd en-US/dita/flexible-classroom/edu-context/out
          ls
          zip -qq -r fc-android-en-doc.zip "android-html5"
          ls
          zip -qq -r fc-ios-en-doc.zip "ios-html5"
          ls
          zip -qq -r fc-android-cn-doc.zip "android-html5-cn"
          ls
          zip -qq -r fc-ios-cn-doc.zip "ios-html5-cn"    
    - name: Upload FC EN Android doc to release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: en-US/dita/flexible-classroom/edu-context/out/fc-android-en-doc.zip
          asset_name: fc-android-en-doc.zip
          tag: main
          overwrite: true
          body: "DITA docs."
    - name: Upload FC EN iOS doc to release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: en-US/dita/flexible-classroom/edu-context/out/fc-ios-en-doc.zip
          asset_name: fc-ios-en-doc.zip
          tag: main
          overwrite: true
          body: "DITA docs."
