# GitHub CI build pipeline
name: Awesome JSON CI build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - release/rtc-ng/3.8.200-framework
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  cd xml2json
                  python -m pip install --upgrade pip
                  if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Run json creation
              run: |
                  cd xml2json
                  echo "Running for Flutter CG"
                  python xml2json.py --working_dir ../en-US/dita/RTC --platform_tag flutter --json_file flutter_newer.json --sdk_type sdk --remove_sdk_type sdk-ng --defined_path flutter
                  echo "Running for CPP NG"
                  python xml2json.py --working_dir ../en-US/dita/RTC-NG --platform_tag cpp --json_file cpp_ng.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path cpp-ng
                  echo "Running for CS CG"
                  python xml2json.py --working_dir ../en-US/dita/RTC --platform_tag cs --json_file csharp_cg.json --sdk_type rtc --remove_sdk_type rtc-ng --defined_path cs
                  echo "Running for unity NG CN (test)"
                  python xml2json.py --working_dir ../dita/RTC-NG --platform_tag unity --json_file unity_ng.json --sdk_type rtc-ng --remove_sdk_type rtc --defined_path unity-ng
            - name: Upload Flutter CG JSON to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/flutter_newer.json
                  asset_name: flutter_doc_template.json
                  tag: main
                  overwrite: true
                  body: "Template file for automatic comment population."
            - name: Upload C++ NG JSON to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/cpp_ng.json
                  asset_name: cpp_ng_doc_template.json
                  tag: main
                  overwrite: true
                  body: "Template file for automatic comment population."
            - name: Upload CS CG JSON to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/csharp_cg.json
                  asset_name: csharp_cg_doc_template.json
                  tag: main
                  overwrite: true
                  body: "Template file for automatic comment population."
            - name: Upload Unity NG JSON to release (CN, test)
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/unity_ng.json
                  asset_name: unity_ng_doc_template.json
                  tag: main
                  overwrite: true
                  body: "Template file for automatic comment population."
