# GitHub CI build pipeline
name: Awesome DITA API doc prototype validation

on:
    push:
        branches:
            - master
            - main
    pull_request:
        branches:
            - master
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  cd xml2json
                  python -m pip install --upgrade pip
                  pip install coverage
                  if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Run CPP validation
              run: |
                  cd xml2json
                  python check_cpp_ng_prototype.py --code_location ./code_to_check/cpp_ng --dita_location ../dita/RTC/API --dita_map_location ../dita/RTC/config/keys-rtc-ng-api-cpp.ditamap --decomment_code_location ./code_to_check/decommented
            - name: Run Java validation
              run: |
                  cd xml2json
                  python check_java_ng_prototype.py --code_location ./code_to_check/java_ng --dita_location ../dita/RTC/API --dita_map_location ../dita/RTC/config/keys-rtc-ng-api-java.ditamap --decomment_code_location ./code_to_check/decommented
            - name: Run OC validation
              run: |
                  cd xml2json
                  python check_oc_ng_prototype.py --code_location ./code_to_check/oc_ng --dita_location ../dita/RTC/API --dita_map_location ../dita/RTC/config/keys-rtc-ng-api-oc.ditamap --decomment_code_location ./code_to_check/decommented
            - name: Run Flutter CG validation
              run: |
                  cd xml2json
                  python check_dart_cg_prototype.py --code_location ./code_to_check/flutter_cg --dita_location ../dita/RTC/API --dita_map_location ../dita/RTC/config/keys-rtc-api-flutter.ditamap --decomment_code_location ./code_to_check/decommented
            - name: Upload CPP NG log TXT to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/prototype_check_cpp_ng.txt
                  asset_name: prototype_check_cpp_ng.txt
                  tag: main
                  overwrite: true
                  body: "Comment release"
            - name: Upload Java NG log TXT to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/prototype_check_java_ng.txt
                  asset_name: prototype_check_java_ng.txt
                  tag: main
                  overwrite: true
                  body: "Comment release"
            - name: Upload OC NG log TXT to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/prototype_check_oc_ng.txt
                  asset_name: prototype_check_oc_ng.txt
                  tag: main
                  overwrite: true
                  body: "Comment release"
            - name: Upload Flutter CG log TXT to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: xml2json/prototype_check_dart_cg.txt
                  asset_name: prototype_check_dart_cg.txt
                  tag: main
                  overwrite: true
                  body: "Comment release"       
