# GitHub CI build pipeline
name: Awesome prototype from code to DITA (Electron)

on:
    workflow_dispatch:

    pull_request:
        branches:
            # - 'release/rtc-ng/3.7.203-unity'
            - '3.8.200-electron-yaxi'
    push:
        branches:
            - '3.8.200-electron-yaxi'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  cd xml2json
                  python -m pip install --upgrade pip
                  pip install coverage
                  if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: fetch proto
              run: |
                  cd xml2json
                  # python extract_proto_and_sync_to_dita_unity.py --code_location ./code_to_check/unity_ng --dita_location ../dita/RTC-NG/API --dita_map_location ../dita/RTC-NG/config/keys-rtc-ng-api-unity.ditamap --decomment_code_location ./code_to_check/decommented
                  # python extract_proto_and_sync_to_dita_flutter.py --code_location ./code_to_check/flutter-ng --dita_location ../dita/RTC-NG/API --dita_map_location ../dita/RTC-NG/config/keys-rtc-ng-api-flutter.ditamap --decomment_code_location ./code_to_check/decommented
                  # python extract_proto_and_sync_to_dita_react_native.py --code_location ./code_to_check/rn_ng --dita_location ../dita/RTC-NG/API --dita_map_location ../dita/RTC-NG/config/keys-rtc-ng-api-rn.ditamap --decomment_code_location ./code_to_check/decommented
                  python extract_proto_and_sync_to_dita_electron.py --code_location ./code_to_check/electron_ng --dita_location ../dita/RTC-NG/API --dita_map_location ../dita/RTC-NG/config/keys-rtc-ng-api-electron.ditamap --decomment_code_location ./code_to_check/decommented
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: Fetch proto
                  title: "[AUTO: MERGE AT YOUR EARLIEST CONVENIENCE] Fetch proto"
                  branch: auto/sync-proto
                  branch-suffix: timestamp
                  delete-branch: true
                  base: 3.8.200-electron-yaxi
                  reviewers: Cilla-luodan
                  body: >
                      This PR is auto-generated to Fetch proto. @HeatherWYL  @Cilla-luodan
                  labels: report, automated pr
